sudo: false
language: ruby
rvm: 2.6.1
cache: bundler
branches:
  only:
    - master
bundler_args: --without production --retry=6
before_script: bundle exec rake --trace db:create db:schema:load db:seed
